### ISSUE TITLE
--cloudos-url failing when trailing backlash is present

### ISSUE THREAD

**Issue by imendes93** [lifebit-ai/cloudos-cli#79]
The following command is working as expected

```bash
cloudos job run --nextflow-profile vcf_ldak_gencor --cloudos-url https://staging.lifebit.ai --apikey XXXXXXXXXX --workspace-id 62569d97ab755c0136140579 --workflow-name bi-traits-nf --project-name downstream-benchmarking --resumable --spot
```

Resulting run -> https://staging.lifebit.ai/public/jobs/62fb8b85c0baa20147b021ba

Unfortunately, is the `--cloudos-url` has a trailing backlash it fails with the following error:

```bash
cloudos job run --nextflow-profile vcf_ldak_gencor --cloudos-url https://staging.lifebit.ai/ --apikey XXXXXXXX --workspace-id 62569d97ab755c0136140579 --workflow-name bi-traits-nf --project-name downstream-benchmarking --resumable --spot
CloudOS python package: a package for interacting with CloudOS.

Version: 1.0.0

CloudOS job functionality: run and check jobs in CloudOS.

Executing run...
Traceback (most recent call last):
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/bin/cloudos", line 8, in <module>
    sys.exit(run_cloudos_cli())
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/site-packages/cloudos/__main__.py", line 169, in run
    workflow_type = cl.detect_workflow(workflow_name, workspace_id)
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/site-packages/cloudos/clos.py", line 258, in detect_workflow
    my_workflows = self.process_workflow_list(my_workflows_r)
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/site-packages/cloudos/clos.py", line 234, in process_workflow_list
    my_workflows = json.loads(r.content)
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/inesmendes/opt/anaconda3/envs/cloudos-api/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cgpu** [comment]
Closing as duplicate of https://github.com/lifebit-ai/cloudos-cli/issues/48
